<?php

namespace App\Mail;

use Illuminate\Bus\Queueable;
use Illuminate\Mail\Mailable;
use Illuminate\Queue\SerializesModels;
use Illuminate\Contracts\Queue\ShouldQueue;

//class NotificationSend extends Mailable
class NotificationSend extends Mailable implements ShouldQueue
{
    use Queueable, SerializesModels;

    public $user_name;
    public $object;
    public $message_txt;

    /**
     * Create a new message instance.
     *
     * @return void
     */
    public function __construct($user_name, $object, $message)
    {
        $this->user_name = $user_name;
        $this->object = $object;
        $this->message_txt = $message;
    }

    /**
     * Build the message.
     *
     * @return $this
     */
    public function build()
    {
        /*
            This Notification email was generated by the RidgeTec Portal.

            DO NOT REPLY TO THIS EMAIL. THIS MAIL BOX IS NOT MONITORED.

            Dear Kevin,

            Please note: 861107030190590 is having SD card read or write errors!
            You can try to format the SD card but you will lose your data. Please replace the SD card.

            Powered by RidgeTec.
        */

        // $this->message_txt = 'Hello World';
        // $this->message_txt = 'Please note SD card errors !';
        // return $this->subject($this->camera_name)
        return $this->subject(config('app.name').' Notification')
                    ->view('emails.notification');
    }
}


/*
http://sample.test:8025/

.env
MAIL_DRIVER=smtp
MAIL_HOST=127.0.0.1
MAIL_PORT=1025
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
*/

/*
MAIL_DRIVER=smtp
MAIL_HOST=smtp.exmail.qq.com
MAIL_PORT=465
MAIL_USERNAME=no-reply@10ware.com
MAIL_PASSWORD=Caperplus7002
MAIL_ENCRYPTION=ssl
MAIL_FROM_ADDRESS=no-reply@10ware.com
MAIL_FROM_NAME=no-reply
*/

/*
Success: You are now registered, but your account is not yet confirmed.
Please look in your inbox for a confirmation email and click the Verify link.
*/