
This email was generated by the KmCam Portal for
camera {{ $camera_name }} owned by {{ $user_name }}

DO NOT REPLY TO THIS EMAIL. THIS MAIL BOX IS NOT MONITORED.

<br>
<img src="{{$message->embed($imgPath)}}">
