@extends('emails.layout')

@section('content')
This email was generated by the KmCam Portal for
camera {{ $camera_name }} owned by {{ $user_name }}

<br>
<h1>DO NOT REPLY TO THIS EMAIL. THIS MAIL BOX IS NOT MONITORED.</h1>

<br>
<img src="{{ $message->embed($imgPath) }}">
@endsection
