@extends('emails.layout')

@section('content')
<h1 style="margin-top: 0; color: #2F3133; font-size: 19px; font-weight: bold; text-align: left;">
    <p>This email was generated by the KMCam Portal for <br/>
        camera {{ $camera_name }} owned by {{ $user_name }}
</h1>

<p style="margin-top: 0; color: #74787E; font-size: 16px; line-height: 1.5em;">
    DO NOT REPLY TO THIS EMAIL.  THIS MAIL BOX IS NOT MONITORED.
</p>

<p>
    <a href=""  target="_blank">
        <img src="{{ $message->embed($imgPath) }}">
    </a>
</p>
@endsection
